# Generated by Django 3.1 on 2022-04-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistenti',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nume', models.CharField(max_length=50)),
                ('Prenume', models.CharField(max_length=50)),
                ('CNP', models.CharField(max_length=50)),
                ('Telefon', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IstoricMedical',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nume_Fisier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medici',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nume', models.CharField(max_length=50)),
                ('Prenume', models.CharField(max_length=50)),
                ('CNP', models.CharField(max_length=50)),
                ('Telefon', models.CharField(max_length=10)),
                ('Specialitate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pacienti',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nume', models.CharField(max_length=50)),
                ('Prenume', models.CharField(max_length=50)),
                ('CNP', models.CharField(max_length=50)),
                ('Telefon', models.CharField(max_length=10)),
                ('Pending_Delete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Programare',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.DateField()),
                ('Ora', models.TimeField()),
                ('Specialitate', models.CharField(max_length=50)),
                ('ID_Medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBApp.medici')),
                ('ID_Pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBApp.pacienti')),
            ],
        ),
        migrations.CreateModel(
            name='Useri',
            fields=[
                ('Email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='pacienti',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBApp.useri'),
        ),
        migrations.AddField(
            model_name='pacienti',
            name='ID_Medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBApp.medici'),
        ),
        migrations.AddField(
            model_name='medici',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBApp.useri'),
        ),
        migrations.AddField(
            model_name='istoricmedical',
            name='ID_Pacient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBApp.pacienti'),
        ),
        migrations.AddField(
            model_name='asistenti',
            name='Email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBApp.useri'),
        ),
        migrations.AddField(
            model_name='asistenti',
            name='ID_Medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBApp.medici'),
        ),
    ]
